// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: class_test_sets.sql

package db

import (
	"context"
)

const addTestSetToClass = `-- name: AddTestSetToClass :exec
INSERT INTO class_test_sets (
    class_id, test_set_id
) VALUES (
    $1, $2
) ON CONFLICT DO NOTHING
`

type AddTestSetToClassParams struct {
	ClassID   int64 `json:"class_id"`
	TestSetID int64 `json:"test_set_id"`
}

func (q *Queries) AddTestSetToClass(ctx context.Context, db DBTX, arg AddTestSetToClassParams) error {
	_, err := db.Exec(ctx, addTestSetToClass, arg.ClassID, arg.TestSetID)
	return err
}

const deleteTestSetFromClass = `-- name: DeleteTestSetFromClass :exec
DELETE FROM class_test_sets
WHERE test_set_id = $1
`

func (q *Queries) DeleteTestSetFromClass(ctx context.Context, db DBTX, testSetID int64) error {
	_, err := db.Exec(ctx, deleteTestSetFromClass, testSetID)
	return err
}
