// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddStudentToClass(ctx context.Context, db DBTX, arg AddStudentToClassParams) (ClassStudent, error)
	AddTestSetToClass(ctx context.Context, db DBTX, arg AddTestSetToClassParams) error
	ClassesCount(ctx context.Context, db DBTX, teacherID int64) (int64, error)
	CreateClass(ctx context.Context, db DBTX, arg CreateClassParams) (Class, error)
	CreateTestSet(ctx context.Context, db DBTX, arg CreateTestSetParams) (TestSet, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	DeleteClass(ctx context.Context, db DBTX, classID int64) error
	DeleteStudentFromClass(ctx context.Context, db DBTX, studentID int64) error
	DeleteTestSet(ctx context.Context, db DBTX, testSetID int64) error
	DeleteTestSetFromClass(ctx context.Context, db DBTX, testSetID int64) error
	DeleteUser(ctx context.Context, db DBTX, userID int64) error
	DeleteWords(ctx context.Context, db DBTX, wordsID int64) error
	GetClassByID(ctx context.Context, db DBTX, classID int64) (Class, error)
	// -- name: ListTestSetsByClassID :many
	// SELECT * FROM test_sets
	// WHERE class_id = $1
	// LIMIT $2
	// OFFSET $3;
	GetTestSetByID(ctx context.Context, db DBTX, testSetID int64) (TestSet, error)
	GetTestSetsCount(ctx context.Context, db DBTX, creatorID int64) (int64, error)
	GetUser(ctx context.Context, db DBTX, userID int64) (User, error)
	InsertWords(ctx context.Context, db DBTX, arg InsertWordsParams) (Word, error)
	ListClassStudents(ctx context.Context, db DBTX, arg ListClassStudentsParams) ([]ClassStudent, error)
	ListClassesByTeacherID(ctx context.Context, db DBTX, arg ListClassesByTeacherIDParams) ([]Class, error)
	// -- name: GetTestSetsByClassID :many
	// SELECT * FROM class_test_sets
	// WHERE class_id = $1;
	ListTestSetsByClassID(ctx context.Context, db DBTX, arg ListTestSetsByClassIDParams) ([]ListTestSetsByClassIDRow, error)
	ListTestSetsByCreatorID(ctx context.Context, db DBTX, arg ListTestSetsByCreatorIDParams) ([]TestSet, error)
	MakeTestSetPublic(ctx context.Context, db DBTX, testSetID int64) error
	NewStudentProgress(ctx context.Context, db DBTX, arg NewStudentProgressParams) (StudentProgress, error)
	NewTestSession(ctx context.Context, db DBTX, arg NewTestSessionParams) (TestSession, error)
}

var _ Querier = (*Queries)(nil)
