// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	AddStudentToClass(ctx context.Context, db DBTX, arg AddStudentToClassParams) (ClassStudent, error)
	AddTestSetToClass(ctx context.Context, db DBTX, arg AddTestSetToClassParams) (ClassTestSet, error)
	CreateClass(ctx context.Context, db DBTX, arg CreateClassParams) (Class, error)
	CreateTestSet(ctx context.Context, db DBTX, arg CreateTestSetParams) (TestSet, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	DeleteClass(ctx context.Context, db DBTX, classID int64) error
	DeleteStudentFromClass(ctx context.Context, db DBTX, studentID int64) error
	DeleteTestSet(ctx context.Context, db DBTX, testSetID int64) error
	DeleteTestSetFromClass(ctx context.Context, db DBTX, testSetID int64) error
	DeleteUser(ctx context.Context, db DBTX, userID int64) error
	DeleteWords(ctx context.Context, db DBTX, wordsID int64) error
	GetUser(ctx context.Context, db DBTX, username string) (User, error)
	InsertWords(ctx context.Context, db DBTX, arg InsertWordsParams) (Word, error)
	ListClassStudents(ctx context.Context, db DBTX, arg ListClassStudentsParams) ([]ClassStudent, error)
	ListClasses(ctx context.Context, db DBTX, arg ListClassesParams) ([]Class, error)
	MakeTestSetPublic(ctx context.Context, db DBTX, testSetID int64) error
	NewStudentProgress(ctx context.Context, db DBTX, arg NewStudentProgressParams) (StudentProgress, error)
	NewTestSession(ctx context.Context, db DBTX, arg NewTestSessionParams) (TestSession, error)
}

var _ Querier = (*Queries)(nil)
