// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: student_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const newStudentProgress = `-- name: NewStudentProgress :one
INSERT INTO student_progress (
    student_id, test_set_id, words_id, correct_count, incorrect_count
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING progress_id, student_id, test_set_id, words_id, correct_count, incorrect_count
`

type NewStudentProgressParams struct {
	StudentID      int64       `json:"student_id"`
	TestSetID      int64       `json:"test_set_id"`
	WordsID        int64       `json:"words_id"`
	CorrectCount   pgtype.Int4 `json:"correct_count"`
	IncorrectCount pgtype.Int4 `json:"incorrect_count"`
}

func (q *Queries) NewStudentProgress(ctx context.Context, db DBTX, arg NewStudentProgressParams) (StudentProgress, error) {
	row := db.QueryRow(ctx, newStudentProgress,
		arg.StudentID,
		arg.TestSetID,
		arg.WordsID,
		arg.CorrectCount,
		arg.IncorrectCount,
	)
	var i StudentProgress
	err := row.Scan(
		&i.ProgressID,
		&i.StudentID,
		&i.TestSetID,
		&i.WordsID,
		&i.CorrectCount,
		&i.IncorrectCount,
	)
	return i, err
}
