// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    telegram_id, full_name, username, "role", phone
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING user_id, telegram_id, full_name, username, role, phone
`

type CreateUserParams struct {
	TelegramID int64  `json:"telegram_id"`
	FullName   string `json:"full_name"`
	Username   string `json:"username"`
	Role       string `json:"role"`
	Phone      int64  `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error) {
	row := db.QueryRow(ctx, createUser,
		arg.TelegramID,
		arg.FullName,
		arg.Username,
		arg.Role,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.TelegramID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Phone,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, db DBTX, userID int64) error {
	_, err := db.Exec(ctx, deleteUser, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, telegram_id, full_name, username, role, phone FROM users
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, db DBTX, userID int64) (User, error) {
	row := db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.TelegramID,
		&i.FullName,
		&i.Username,
		&i.Role,
		&i.Phone,
	)
	return i, err
}
